
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `SavedCode` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model SavedCode
 * 
 */
export type SavedCodeModel = runtime.Types.Result.DefaultSelection<Prisma.$SavedCodePayload>

export type AggregateSavedCode = {
  _count: SavedCodeCountAggregateOutputType | null
  _min: SavedCodeMinAggregateOutputType | null
  _max: SavedCodeMaxAggregateOutputType | null
}

export type SavedCodeMinAggregateOutputType = {
  id: string | null
  title: string | null
  code: string | null
  createdAt: Date | null
  updatedAt: Date | null
  userId: string | null
  shared: boolean | null
}

export type SavedCodeMaxAggregateOutputType = {
  id: string | null
  title: string | null
  code: string | null
  createdAt: Date | null
  updatedAt: Date | null
  userId: string | null
  shared: boolean | null
}

export type SavedCodeCountAggregateOutputType = {
  id: number
  title: number
  code: number
  createdAt: number
  updatedAt: number
  userId: number
  shared: number
  _all: number
}


export type SavedCodeMinAggregateInputType = {
  id?: true
  title?: true
  code?: true
  createdAt?: true
  updatedAt?: true
  userId?: true
  shared?: true
}

export type SavedCodeMaxAggregateInputType = {
  id?: true
  title?: true
  code?: true
  createdAt?: true
  updatedAt?: true
  userId?: true
  shared?: true
}

export type SavedCodeCountAggregateInputType = {
  id?: true
  title?: true
  code?: true
  createdAt?: true
  updatedAt?: true
  userId?: true
  shared?: true
  _all?: true
}

export type SavedCodeAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which SavedCode to aggregate.
   */
  where?: Prisma.SavedCodeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SavedCodes to fetch.
   */
  orderBy?: Prisma.SavedCodeOrderByWithRelationInput | Prisma.SavedCodeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.SavedCodeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SavedCodes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SavedCodes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned SavedCodes
  **/
  _count?: true | SavedCodeCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: SavedCodeMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: SavedCodeMaxAggregateInputType
}

export type GetSavedCodeAggregateType<T extends SavedCodeAggregateArgs> = {
      [P in keyof T & keyof AggregateSavedCode]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateSavedCode[P]>
    : Prisma.GetScalarType<T[P], AggregateSavedCode[P]>
}




export type SavedCodeGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.SavedCodeWhereInput
  orderBy?: Prisma.SavedCodeOrderByWithAggregationInput | Prisma.SavedCodeOrderByWithAggregationInput[]
  by: Prisma.SavedCodeScalarFieldEnum[] | Prisma.SavedCodeScalarFieldEnum
  having?: Prisma.SavedCodeScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: SavedCodeCountAggregateInputType | true
  _min?: SavedCodeMinAggregateInputType
  _max?: SavedCodeMaxAggregateInputType
}

export type SavedCodeGroupByOutputType = {
  id: string
  title: string
  code: string
  createdAt: Date
  updatedAt: Date
  userId: string
  shared: boolean
  _count: SavedCodeCountAggregateOutputType | null
  _min: SavedCodeMinAggregateOutputType | null
  _max: SavedCodeMaxAggregateOutputType | null
}

type GetSavedCodeGroupByPayload<T extends SavedCodeGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<SavedCodeGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof SavedCodeGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], SavedCodeGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], SavedCodeGroupByOutputType[P]>
      }
    >
  >



export type SavedCodeWhereInput = {
  AND?: Prisma.SavedCodeWhereInput | Prisma.SavedCodeWhereInput[]
  OR?: Prisma.SavedCodeWhereInput[]
  NOT?: Prisma.SavedCodeWhereInput | Prisma.SavedCodeWhereInput[]
  id?: Prisma.StringFilter<"SavedCode"> | string
  title?: Prisma.StringFilter<"SavedCode"> | string
  code?: Prisma.StringFilter<"SavedCode"> | string
  createdAt?: Prisma.DateTimeFilter<"SavedCode"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"SavedCode"> | Date | string
  userId?: Prisma.StringFilter<"SavedCode"> | string
  shared?: Prisma.BoolFilter<"SavedCode"> | boolean
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}

export type SavedCodeOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  code?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  shared?: Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
}

export type SavedCodeWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.SavedCodeWhereInput | Prisma.SavedCodeWhereInput[]
  OR?: Prisma.SavedCodeWhereInput[]
  NOT?: Prisma.SavedCodeWhereInput | Prisma.SavedCodeWhereInput[]
  title?: Prisma.StringFilter<"SavedCode"> | string
  code?: Prisma.StringFilter<"SavedCode"> | string
  createdAt?: Prisma.DateTimeFilter<"SavedCode"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"SavedCode"> | Date | string
  userId?: Prisma.StringFilter<"SavedCode"> | string
  shared?: Prisma.BoolFilter<"SavedCode"> | boolean
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}, "id">

export type SavedCodeOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  code?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  shared?: Prisma.SortOrder
  _count?: Prisma.SavedCodeCountOrderByAggregateInput
  _max?: Prisma.SavedCodeMaxOrderByAggregateInput
  _min?: Prisma.SavedCodeMinOrderByAggregateInput
}

export type SavedCodeScalarWhereWithAggregatesInput = {
  AND?: Prisma.SavedCodeScalarWhereWithAggregatesInput | Prisma.SavedCodeScalarWhereWithAggregatesInput[]
  OR?: Prisma.SavedCodeScalarWhereWithAggregatesInput[]
  NOT?: Prisma.SavedCodeScalarWhereWithAggregatesInput | Prisma.SavedCodeScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"SavedCode"> | string
  title?: Prisma.StringWithAggregatesFilter<"SavedCode"> | string
  code?: Prisma.StringWithAggregatesFilter<"SavedCode"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"SavedCode"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"SavedCode"> | Date | string
  userId?: Prisma.StringWithAggregatesFilter<"SavedCode"> | string
  shared?: Prisma.BoolWithAggregatesFilter<"SavedCode"> | boolean
}

export type SavedCodeCreateInput = {
  id?: string
  title: string
  code: string
  createdAt?: Date | string
  updatedAt?: Date | string
  shared?: boolean
  user: Prisma.UserCreateNestedOneWithoutSavedCodesInput
}

export type SavedCodeUncheckedCreateInput = {
  id?: string
  title: string
  code: string
  createdAt?: Date | string
  updatedAt?: Date | string
  userId: string
  shared?: boolean
}

export type SavedCodeUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  shared?: Prisma.BoolFieldUpdateOperationsInput | boolean
  user?: Prisma.UserUpdateOneRequiredWithoutSavedCodesNestedInput
}

export type SavedCodeUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  shared?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type SavedCodeCreateManyInput = {
  id?: string
  title: string
  code: string
  createdAt?: Date | string
  updatedAt?: Date | string
  userId: string
  shared?: boolean
}

export type SavedCodeUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  shared?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type SavedCodeUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  shared?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type SavedCodeListRelationFilter = {
  every?: Prisma.SavedCodeWhereInput
  some?: Prisma.SavedCodeWhereInput
  none?: Prisma.SavedCodeWhereInput
}

export type SavedCodeOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type SavedCodeCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  code?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  shared?: Prisma.SortOrder
}

export type SavedCodeMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  code?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  shared?: Prisma.SortOrder
}

export type SavedCodeMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  code?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  shared?: Prisma.SortOrder
}

export type SavedCodeCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.SavedCodeCreateWithoutUserInput, Prisma.SavedCodeUncheckedCreateWithoutUserInput> | Prisma.SavedCodeCreateWithoutUserInput[] | Prisma.SavedCodeUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.SavedCodeCreateOrConnectWithoutUserInput | Prisma.SavedCodeCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.SavedCodeCreateManyUserInputEnvelope
  connect?: Prisma.SavedCodeWhereUniqueInput | Prisma.SavedCodeWhereUniqueInput[]
}

export type SavedCodeUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.SavedCodeCreateWithoutUserInput, Prisma.SavedCodeUncheckedCreateWithoutUserInput> | Prisma.SavedCodeCreateWithoutUserInput[] | Prisma.SavedCodeUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.SavedCodeCreateOrConnectWithoutUserInput | Prisma.SavedCodeCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.SavedCodeCreateManyUserInputEnvelope
  connect?: Prisma.SavedCodeWhereUniqueInput | Prisma.SavedCodeWhereUniqueInput[]
}

export type SavedCodeUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.SavedCodeCreateWithoutUserInput, Prisma.SavedCodeUncheckedCreateWithoutUserInput> | Prisma.SavedCodeCreateWithoutUserInput[] | Prisma.SavedCodeUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.SavedCodeCreateOrConnectWithoutUserInput | Prisma.SavedCodeCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.SavedCodeUpsertWithWhereUniqueWithoutUserInput | Prisma.SavedCodeUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.SavedCodeCreateManyUserInputEnvelope
  set?: Prisma.SavedCodeWhereUniqueInput | Prisma.SavedCodeWhereUniqueInput[]
  disconnect?: Prisma.SavedCodeWhereUniqueInput | Prisma.SavedCodeWhereUniqueInput[]
  delete?: Prisma.SavedCodeWhereUniqueInput | Prisma.SavedCodeWhereUniqueInput[]
  connect?: Prisma.SavedCodeWhereUniqueInput | Prisma.SavedCodeWhereUniqueInput[]
  update?: Prisma.SavedCodeUpdateWithWhereUniqueWithoutUserInput | Prisma.SavedCodeUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.SavedCodeUpdateManyWithWhereWithoutUserInput | Prisma.SavedCodeUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.SavedCodeScalarWhereInput | Prisma.SavedCodeScalarWhereInput[]
}

export type SavedCodeUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.SavedCodeCreateWithoutUserInput, Prisma.SavedCodeUncheckedCreateWithoutUserInput> | Prisma.SavedCodeCreateWithoutUserInput[] | Prisma.SavedCodeUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.SavedCodeCreateOrConnectWithoutUserInput | Prisma.SavedCodeCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.SavedCodeUpsertWithWhereUniqueWithoutUserInput | Prisma.SavedCodeUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.SavedCodeCreateManyUserInputEnvelope
  set?: Prisma.SavedCodeWhereUniqueInput | Prisma.SavedCodeWhereUniqueInput[]
  disconnect?: Prisma.SavedCodeWhereUniqueInput | Prisma.SavedCodeWhereUniqueInput[]
  delete?: Prisma.SavedCodeWhereUniqueInput | Prisma.SavedCodeWhereUniqueInput[]
  connect?: Prisma.SavedCodeWhereUniqueInput | Prisma.SavedCodeWhereUniqueInput[]
  update?: Prisma.SavedCodeUpdateWithWhereUniqueWithoutUserInput | Prisma.SavedCodeUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.SavedCodeUpdateManyWithWhereWithoutUserInput | Prisma.SavedCodeUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.SavedCodeScalarWhereInput | Prisma.SavedCodeScalarWhereInput[]
}

export type BoolFieldUpdateOperationsInput = {
  set?: boolean
}

export type SavedCodeCreateWithoutUserInput = {
  id?: string
  title: string
  code: string
  createdAt?: Date | string
  updatedAt?: Date | string
  shared?: boolean
}

export type SavedCodeUncheckedCreateWithoutUserInput = {
  id?: string
  title: string
  code: string
  createdAt?: Date | string
  updatedAt?: Date | string
  shared?: boolean
}

export type SavedCodeCreateOrConnectWithoutUserInput = {
  where: Prisma.SavedCodeWhereUniqueInput
  create: Prisma.XOR<Prisma.SavedCodeCreateWithoutUserInput, Prisma.SavedCodeUncheckedCreateWithoutUserInput>
}

export type SavedCodeCreateManyUserInputEnvelope = {
  data: Prisma.SavedCodeCreateManyUserInput | Prisma.SavedCodeCreateManyUserInput[]
}

export type SavedCodeUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.SavedCodeWhereUniqueInput
  update: Prisma.XOR<Prisma.SavedCodeUpdateWithoutUserInput, Prisma.SavedCodeUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.SavedCodeCreateWithoutUserInput, Prisma.SavedCodeUncheckedCreateWithoutUserInput>
}

export type SavedCodeUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.SavedCodeWhereUniqueInput
  data: Prisma.XOR<Prisma.SavedCodeUpdateWithoutUserInput, Prisma.SavedCodeUncheckedUpdateWithoutUserInput>
}

export type SavedCodeUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.SavedCodeScalarWhereInput
  data: Prisma.XOR<Prisma.SavedCodeUpdateManyMutationInput, Prisma.SavedCodeUncheckedUpdateManyWithoutUserInput>
}

export type SavedCodeScalarWhereInput = {
  AND?: Prisma.SavedCodeScalarWhereInput | Prisma.SavedCodeScalarWhereInput[]
  OR?: Prisma.SavedCodeScalarWhereInput[]
  NOT?: Prisma.SavedCodeScalarWhereInput | Prisma.SavedCodeScalarWhereInput[]
  id?: Prisma.StringFilter<"SavedCode"> | string
  title?: Prisma.StringFilter<"SavedCode"> | string
  code?: Prisma.StringFilter<"SavedCode"> | string
  createdAt?: Prisma.DateTimeFilter<"SavedCode"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"SavedCode"> | Date | string
  userId?: Prisma.StringFilter<"SavedCode"> | string
  shared?: Prisma.BoolFilter<"SavedCode"> | boolean
}

export type SavedCodeCreateManyUserInput = {
  id?: string
  title: string
  code: string
  createdAt?: Date | string
  updatedAt?: Date | string
  shared?: boolean
}

export type SavedCodeUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  shared?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type SavedCodeUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  shared?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type SavedCodeUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  shared?: Prisma.BoolFieldUpdateOperationsInput | boolean
}



export type SavedCodeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  code?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  userId?: boolean
  shared?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["savedCode"]>

export type SavedCodeSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  code?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  userId?: boolean
  shared?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["savedCode"]>

export type SavedCodeSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  code?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  userId?: boolean
  shared?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["savedCode"]>

export type SavedCodeSelectScalar = {
  id?: boolean
  title?: boolean
  code?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  userId?: boolean
  shared?: boolean
}

export type SavedCodeOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "title" | "code" | "createdAt" | "updatedAt" | "userId" | "shared", ExtArgs["result"]["savedCode"]>
export type SavedCodeInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type SavedCodeIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type SavedCodeIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $SavedCodePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "SavedCode"
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    title: string
    code: string
    createdAt: Date
    updatedAt: Date
    userId: string
    shared: boolean
  }, ExtArgs["result"]["savedCode"]>
  composites: {}
}

export type SavedCodeGetPayload<S extends boolean | null | undefined | SavedCodeDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$SavedCodePayload, S>

export type SavedCodeCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<SavedCodeFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: SavedCodeCountAggregateInputType | true
  }

export interface SavedCodeDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['SavedCode'], meta: { name: 'SavedCode' } }
  /**
   * Find zero or one SavedCode that matches the filter.
   * @param {SavedCodeFindUniqueArgs} args - Arguments to find a SavedCode
   * @example
   * // Get one SavedCode
   * const savedCode = await prisma.savedCode.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends SavedCodeFindUniqueArgs>(args: Prisma.SelectSubset<T, SavedCodeFindUniqueArgs<ExtArgs>>): Prisma.Prisma__SavedCodeClient<runtime.Types.Result.GetResult<Prisma.$SavedCodePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one SavedCode that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {SavedCodeFindUniqueOrThrowArgs} args - Arguments to find a SavedCode
   * @example
   * // Get one SavedCode
   * const savedCode = await prisma.savedCode.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends SavedCodeFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, SavedCodeFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__SavedCodeClient<runtime.Types.Result.GetResult<Prisma.$SavedCodePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first SavedCode that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SavedCodeFindFirstArgs} args - Arguments to find a SavedCode
   * @example
   * // Get one SavedCode
   * const savedCode = await prisma.savedCode.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends SavedCodeFindFirstArgs>(args?: Prisma.SelectSubset<T, SavedCodeFindFirstArgs<ExtArgs>>): Prisma.Prisma__SavedCodeClient<runtime.Types.Result.GetResult<Prisma.$SavedCodePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first SavedCode that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SavedCodeFindFirstOrThrowArgs} args - Arguments to find a SavedCode
   * @example
   * // Get one SavedCode
   * const savedCode = await prisma.savedCode.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends SavedCodeFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, SavedCodeFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__SavedCodeClient<runtime.Types.Result.GetResult<Prisma.$SavedCodePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more SavedCodes that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SavedCodeFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all SavedCodes
   * const savedCodes = await prisma.savedCode.findMany()
   * 
   * // Get first 10 SavedCodes
   * const savedCodes = await prisma.savedCode.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const savedCodeWithIdOnly = await prisma.savedCode.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends SavedCodeFindManyArgs>(args?: Prisma.SelectSubset<T, SavedCodeFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SavedCodePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a SavedCode.
   * @param {SavedCodeCreateArgs} args - Arguments to create a SavedCode.
   * @example
   * // Create one SavedCode
   * const SavedCode = await prisma.savedCode.create({
   *   data: {
   *     // ... data to create a SavedCode
   *   }
   * })
   * 
   */
  create<T extends SavedCodeCreateArgs>(args: Prisma.SelectSubset<T, SavedCodeCreateArgs<ExtArgs>>): Prisma.Prisma__SavedCodeClient<runtime.Types.Result.GetResult<Prisma.$SavedCodePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many SavedCodes.
   * @param {SavedCodeCreateManyArgs} args - Arguments to create many SavedCodes.
   * @example
   * // Create many SavedCodes
   * const savedCode = await prisma.savedCode.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends SavedCodeCreateManyArgs>(args?: Prisma.SelectSubset<T, SavedCodeCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many SavedCodes and returns the data saved in the database.
   * @param {SavedCodeCreateManyAndReturnArgs} args - Arguments to create many SavedCodes.
   * @example
   * // Create many SavedCodes
   * const savedCode = await prisma.savedCode.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many SavedCodes and only return the `id`
   * const savedCodeWithIdOnly = await prisma.savedCode.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends SavedCodeCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, SavedCodeCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SavedCodePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a SavedCode.
   * @param {SavedCodeDeleteArgs} args - Arguments to delete one SavedCode.
   * @example
   * // Delete one SavedCode
   * const SavedCode = await prisma.savedCode.delete({
   *   where: {
   *     // ... filter to delete one SavedCode
   *   }
   * })
   * 
   */
  delete<T extends SavedCodeDeleteArgs>(args: Prisma.SelectSubset<T, SavedCodeDeleteArgs<ExtArgs>>): Prisma.Prisma__SavedCodeClient<runtime.Types.Result.GetResult<Prisma.$SavedCodePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one SavedCode.
   * @param {SavedCodeUpdateArgs} args - Arguments to update one SavedCode.
   * @example
   * // Update one SavedCode
   * const savedCode = await prisma.savedCode.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends SavedCodeUpdateArgs>(args: Prisma.SelectSubset<T, SavedCodeUpdateArgs<ExtArgs>>): Prisma.Prisma__SavedCodeClient<runtime.Types.Result.GetResult<Prisma.$SavedCodePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more SavedCodes.
   * @param {SavedCodeDeleteManyArgs} args - Arguments to filter SavedCodes to delete.
   * @example
   * // Delete a few SavedCodes
   * const { count } = await prisma.savedCode.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends SavedCodeDeleteManyArgs>(args?: Prisma.SelectSubset<T, SavedCodeDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more SavedCodes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SavedCodeUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many SavedCodes
   * const savedCode = await prisma.savedCode.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends SavedCodeUpdateManyArgs>(args: Prisma.SelectSubset<T, SavedCodeUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more SavedCodes and returns the data updated in the database.
   * @param {SavedCodeUpdateManyAndReturnArgs} args - Arguments to update many SavedCodes.
   * @example
   * // Update many SavedCodes
   * const savedCode = await prisma.savedCode.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more SavedCodes and only return the `id`
   * const savedCodeWithIdOnly = await prisma.savedCode.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends SavedCodeUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, SavedCodeUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SavedCodePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one SavedCode.
   * @param {SavedCodeUpsertArgs} args - Arguments to update or create a SavedCode.
   * @example
   * // Update or create a SavedCode
   * const savedCode = await prisma.savedCode.upsert({
   *   create: {
   *     // ... data to create a SavedCode
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the SavedCode we want to update
   *   }
   * })
   */
  upsert<T extends SavedCodeUpsertArgs>(args: Prisma.SelectSubset<T, SavedCodeUpsertArgs<ExtArgs>>): Prisma.Prisma__SavedCodeClient<runtime.Types.Result.GetResult<Prisma.$SavedCodePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of SavedCodes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SavedCodeCountArgs} args - Arguments to filter SavedCodes to count.
   * @example
   * // Count the number of SavedCodes
   * const count = await prisma.savedCode.count({
   *   where: {
   *     // ... the filter for the SavedCodes we want to count
   *   }
   * })
  **/
  count<T extends SavedCodeCountArgs>(
    args?: Prisma.Subset<T, SavedCodeCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], SavedCodeCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a SavedCode.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SavedCodeAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends SavedCodeAggregateArgs>(args: Prisma.Subset<T, SavedCodeAggregateArgs>): Prisma.PrismaPromise<GetSavedCodeAggregateType<T>>

  /**
   * Group by SavedCode.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SavedCodeGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends SavedCodeGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: SavedCodeGroupByArgs['orderBy'] }
      : { orderBy?: SavedCodeGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, SavedCodeGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetSavedCodeGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the SavedCode model
 */
readonly fields: SavedCodeFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for SavedCode.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__SavedCodeClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the SavedCode model
 */
export interface SavedCodeFieldRefs {
  readonly id: Prisma.FieldRef<"SavedCode", 'String'>
  readonly title: Prisma.FieldRef<"SavedCode", 'String'>
  readonly code: Prisma.FieldRef<"SavedCode", 'String'>
  readonly createdAt: Prisma.FieldRef<"SavedCode", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"SavedCode", 'DateTime'>
  readonly userId: Prisma.FieldRef<"SavedCode", 'String'>
  readonly shared: Prisma.FieldRef<"SavedCode", 'Boolean'>
}
    

// Custom InputTypes
/**
 * SavedCode findUnique
 */
export type SavedCodeFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SavedCode
   */
  select?: Prisma.SavedCodeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SavedCode
   */
  omit?: Prisma.SavedCodeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SavedCodeInclude<ExtArgs> | null
  /**
   * Filter, which SavedCode to fetch.
   */
  where: Prisma.SavedCodeWhereUniqueInput
}

/**
 * SavedCode findUniqueOrThrow
 */
export type SavedCodeFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SavedCode
   */
  select?: Prisma.SavedCodeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SavedCode
   */
  omit?: Prisma.SavedCodeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SavedCodeInclude<ExtArgs> | null
  /**
   * Filter, which SavedCode to fetch.
   */
  where: Prisma.SavedCodeWhereUniqueInput
}

/**
 * SavedCode findFirst
 */
export type SavedCodeFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SavedCode
   */
  select?: Prisma.SavedCodeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SavedCode
   */
  omit?: Prisma.SavedCodeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SavedCodeInclude<ExtArgs> | null
  /**
   * Filter, which SavedCode to fetch.
   */
  where?: Prisma.SavedCodeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SavedCodes to fetch.
   */
  orderBy?: Prisma.SavedCodeOrderByWithRelationInput | Prisma.SavedCodeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for SavedCodes.
   */
  cursor?: Prisma.SavedCodeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SavedCodes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SavedCodes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SavedCodes.
   */
  distinct?: Prisma.SavedCodeScalarFieldEnum | Prisma.SavedCodeScalarFieldEnum[]
}

/**
 * SavedCode findFirstOrThrow
 */
export type SavedCodeFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SavedCode
   */
  select?: Prisma.SavedCodeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SavedCode
   */
  omit?: Prisma.SavedCodeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SavedCodeInclude<ExtArgs> | null
  /**
   * Filter, which SavedCode to fetch.
   */
  where?: Prisma.SavedCodeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SavedCodes to fetch.
   */
  orderBy?: Prisma.SavedCodeOrderByWithRelationInput | Prisma.SavedCodeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for SavedCodes.
   */
  cursor?: Prisma.SavedCodeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SavedCodes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SavedCodes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SavedCodes.
   */
  distinct?: Prisma.SavedCodeScalarFieldEnum | Prisma.SavedCodeScalarFieldEnum[]
}

/**
 * SavedCode findMany
 */
export type SavedCodeFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SavedCode
   */
  select?: Prisma.SavedCodeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SavedCode
   */
  omit?: Prisma.SavedCodeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SavedCodeInclude<ExtArgs> | null
  /**
   * Filter, which SavedCodes to fetch.
   */
  where?: Prisma.SavedCodeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SavedCodes to fetch.
   */
  orderBy?: Prisma.SavedCodeOrderByWithRelationInput | Prisma.SavedCodeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing SavedCodes.
   */
  cursor?: Prisma.SavedCodeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SavedCodes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SavedCodes.
   */
  skip?: number
  distinct?: Prisma.SavedCodeScalarFieldEnum | Prisma.SavedCodeScalarFieldEnum[]
}

/**
 * SavedCode create
 */
export type SavedCodeCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SavedCode
   */
  select?: Prisma.SavedCodeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SavedCode
   */
  omit?: Prisma.SavedCodeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SavedCodeInclude<ExtArgs> | null
  /**
   * The data needed to create a SavedCode.
   */
  data: Prisma.XOR<Prisma.SavedCodeCreateInput, Prisma.SavedCodeUncheckedCreateInput>
}

/**
 * SavedCode createMany
 */
export type SavedCodeCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many SavedCodes.
   */
  data: Prisma.SavedCodeCreateManyInput | Prisma.SavedCodeCreateManyInput[]
}

/**
 * SavedCode createManyAndReturn
 */
export type SavedCodeCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SavedCode
   */
  select?: Prisma.SavedCodeSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the SavedCode
   */
  omit?: Prisma.SavedCodeOmit<ExtArgs> | null
  /**
   * The data used to create many SavedCodes.
   */
  data: Prisma.SavedCodeCreateManyInput | Prisma.SavedCodeCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SavedCodeIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * SavedCode update
 */
export type SavedCodeUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SavedCode
   */
  select?: Prisma.SavedCodeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SavedCode
   */
  omit?: Prisma.SavedCodeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SavedCodeInclude<ExtArgs> | null
  /**
   * The data needed to update a SavedCode.
   */
  data: Prisma.XOR<Prisma.SavedCodeUpdateInput, Prisma.SavedCodeUncheckedUpdateInput>
  /**
   * Choose, which SavedCode to update.
   */
  where: Prisma.SavedCodeWhereUniqueInput
}

/**
 * SavedCode updateMany
 */
export type SavedCodeUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update SavedCodes.
   */
  data: Prisma.XOR<Prisma.SavedCodeUpdateManyMutationInput, Prisma.SavedCodeUncheckedUpdateManyInput>
  /**
   * Filter which SavedCodes to update
   */
  where?: Prisma.SavedCodeWhereInput
  /**
   * Limit how many SavedCodes to update.
   */
  limit?: number
}

/**
 * SavedCode updateManyAndReturn
 */
export type SavedCodeUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SavedCode
   */
  select?: Prisma.SavedCodeSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the SavedCode
   */
  omit?: Prisma.SavedCodeOmit<ExtArgs> | null
  /**
   * The data used to update SavedCodes.
   */
  data: Prisma.XOR<Prisma.SavedCodeUpdateManyMutationInput, Prisma.SavedCodeUncheckedUpdateManyInput>
  /**
   * Filter which SavedCodes to update
   */
  where?: Prisma.SavedCodeWhereInput
  /**
   * Limit how many SavedCodes to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SavedCodeIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * SavedCode upsert
 */
export type SavedCodeUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SavedCode
   */
  select?: Prisma.SavedCodeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SavedCode
   */
  omit?: Prisma.SavedCodeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SavedCodeInclude<ExtArgs> | null
  /**
   * The filter to search for the SavedCode to update in case it exists.
   */
  where: Prisma.SavedCodeWhereUniqueInput
  /**
   * In case the SavedCode found by the `where` argument doesn't exist, create a new SavedCode with this data.
   */
  create: Prisma.XOR<Prisma.SavedCodeCreateInput, Prisma.SavedCodeUncheckedCreateInput>
  /**
   * In case the SavedCode was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.SavedCodeUpdateInput, Prisma.SavedCodeUncheckedUpdateInput>
}

/**
 * SavedCode delete
 */
export type SavedCodeDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SavedCode
   */
  select?: Prisma.SavedCodeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SavedCode
   */
  omit?: Prisma.SavedCodeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SavedCodeInclude<ExtArgs> | null
  /**
   * Filter which SavedCode to delete.
   */
  where: Prisma.SavedCodeWhereUniqueInput
}

/**
 * SavedCode deleteMany
 */
export type SavedCodeDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which SavedCodes to delete
   */
  where?: Prisma.SavedCodeWhereInput
  /**
   * Limit how many SavedCodes to delete.
   */
  limit?: number
}

/**
 * SavedCode without action
 */
export type SavedCodeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SavedCode
   */
  select?: Prisma.SavedCodeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SavedCode
   */
  omit?: Prisma.SavedCodeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SavedCodeInclude<ExtArgs> | null
}
